# Generated by Django 2.2.16 on 2020-09-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200906_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('software', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
