# Generated by Django 2.2.16 on 2020-09-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20200909_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.FileField(upload_to=None),
        ),
    ]
