# Generated by Django 2.2.16 on 2020-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20200910_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='resources',
            name='software',
            field=models.CharField(default='', max_length=200),
        ),
    ]
