# Generated by Django 2.2.16 on 2020-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20200910_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='resources',
            name='software',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
